spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wisdom scenic spot?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
server:
  port: 9000
  tomcat:
    uri-encoding: UTF-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zyg.smt.model
system:
  whiteList:
    - /login/logging
    - /login/login
    - /login/toReg
    - /login/reg
    - /login/toForget
    - /login/forget
    - /login/verifyCode